spring:
  application:
    name: datssnake

x-auth-token: ccf5f1fe-e82f-46c5-b592-e240d66ab2aa
---

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    openfeign:
      client:
        config:
          dats-snake-2-client:
            url: "https://games-test.datsteam.dev"

---

spring:
    config:
        activate:
            on-profile: prod
    cloud:
        openfeign:
            client:
                config:
                    dats-snake-2-client:
                        url: "https://games.datsteam.dev"



feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
